-- =========================================================
-- SHAMIRPET.CITY SUPABASE SEED DATA
-- Location: /supabase/seed.sql
-- Run this script in the Supabase SQL Editor after running schema.sql
-- to populate Businesses, Wellness & Healthcare, Real Estate, and Education.
-- =========================================================

INSERT INTO public.places (
  id, name, slug, category, subcategory, village_area, rating, reviews_count, address, phone, email, website, google_maps_url, hours, description, is_featured, verified_status, badge_text, lat, lng, image_url, tags, price_range
) VALUES 
(
  'shamirpet-primary-health-centre',
  'Government Primary Health Centre (PHC) Shamirpet',
  'government-primary-health-centre-shamirpet',
  'Wellness & Healthcare',
  'Hospital & Urgent Care',
  'Shamirpet Junction',
  4.5,
  184,
  'Near Police Station, Main Road, Shamirpet, Medchal-Malkajgiri, Telangana 500078',
  '+91 40 2795 2341',
  NULL,
  NULL,
  'https://maps.google.com/?q=Primary+Health+Centre+Shamirpet',
  'Open 24 Hours (Emergency Services)',
  'Key public emergency and primary care medical facility catering to Shamirpet, Majeedpur, and surrounding Genome Valley workforce with 24x7 ambulance support and outpatient care.',
  TRUE,
  'Verified Healthcare',
  '24x7 Emergency Care',
  17.5954,
  78.5682,
  'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&auto=format&fit=crop&q=80',
  ARRAY['Hospital', 'Emergency', 'Primary Health', 'Ambulance', 'Pediatrics', '24x7'],
  NULL
),
(
  'sanjeevani-multi-speciality-hospital',
  'Sanjeevani Multi-Speciality Clinic & Diagnostic Center',
  'sanjeevani-multi-speciality-clinic-shamirpet',
  'Wellness & Healthcare',
  'Multi-Speciality Clinic',
  'ORR Exit 7',
  4.7,
  312,
  'Plot 42, ORR Service Road, Near Exit 7, Shamirpet, Telangana 500078',
  '+91 98490 12345',
  'care@sanjeevanishamirpet.com',
  'https://sanjeevanihospital.example.com',
  'https://maps.google.com/?q=Sanjeevani+Clinic+Shamirpet',
  '7:30 AM - 10:00 PM',
  'Modern diagnostic centre equipped with digital X-Ray, CT Scan, Pathology lab, General Medicine, Cardiology, and Gynecology consultations.',
  TRUE,
  'Verified Healthcare',
  'Advanced Diagnostics',
  17.5892,
  78.5721,
  'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&auto=format&fit=crop&q=80',
  ARRAY['Diagnostics', 'CT Scan', 'Pathology Lab', 'Cardiology', 'OPD'],
  NULL
),
(
  'celebrity-club-villas-shamirpet',
  'Celebrity Club & Luxury Resort Villas',
  'celebrity-club-and-resort-villas-shamirpet',
  'Real Estate',
  'Gated Villa Community',
  'Lake Circle',
  4.8,
  890,
  'Survey No. 410, Near Shamirpet Lake, Hyderabad, Telangana 500078',
  '+91 40 6789 1100',
  'sales@celebrityvillas.com',
  'https://celebrityvillas.example.com',
  'https://maps.google.com/?q=Celebrity+Club+Villas+Shamirpet',
  '9:00 AM - 7:00 PM',
  'Sprawling 210-acre premium gated villa community featuring 3 & 4 BHK luxury independent villas, clubhouse, swimming pools, tennis courts, and lush landscaping.',
  TRUE,
  'Verified Real Estate',
  'Premium Gated Villas',
  17.6110,
  78.5605,
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
  ARRAY['Luxury Villas', 'Gated Community', 'Clubhouse', 'Swimming Pool', 'Resort Living'],
  '₹1.8 Cr - ₹4.5 Cr'
),
(
  'bharat-biotech-genome-valley',
  'Bharat Biotech Campus (Covaxin Innovation Hub)',
  'bharat-biotech-genome-valley-campus',
  'Businesses',
  'Biotech & Life Sciences',
  'Genome Valley Phase 1',
  4.9,
  1420,
  'Genome Valley, Turkapally, Shamirpet, Hyderabad, Telangana 500078',
  '+91 40 2348 0567',
  'info@bharatbiotech.com',
  'https://bharatbiotech.com',
  'https://maps.google.com/?q=Bharat+Biotech+Genome+Valley+Shamirpet',
  '8:30 AM - 5:30 PM (Mon-Sat)',
  'Global pioneer in vaccine research and biopharmaceuticals. Main manufacturing & R&D facility responsible for developing Covaxin.',
  TRUE,
  'Verified Business',
  'Global Vaccine Leader',
  17.6320,
  78.6015,
  'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80',
  ARRAY['Biotech', 'Vaccine R&D', 'Pharma Giant', 'Genome Valley', 'Global Employer'],
  NULL
),
(
  'bits-pilani-hyderabad-campus',
  'BITS Pilani – Hyderabad Campus',
  'bits-pilani-hyderabad-campus-shamirpet',
  'Education & Research',
  'University & Engineering Institute',
  'Ponnal',
  4.9,
  2850,
  'Jawahar Nagar, Kapra Mandal, Near Shamirpet, Telangana 500078',
  '+91 40 6630 3999',
  NULL,
  'https://bits-pilani.ac.in/hyderabad/',
  'https://maps.google.com/?q=BITS+Pilani+Hyderabad+Campus',
  '8:00 AM - 7:00 PM',
  'Premier national institute of technology and higher research spanning 200 sprawling green acres.',
  TRUE,
  'Verified Institutional',
  'Premier University',
  17.5449,
  78.5718,
  'https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop&q=80',
  ARRAY['University', 'Engineering', 'BITS Pilani', 'Higher Education', 'Research Hub'],
  NULL
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  updated_at = NOW();
